### ISSUE TITLE
Rokoko Plug in for UE5 is not compiling 

### ISSUE THREAD

**Issue by giorgosg12** [Rokoko/rokoko-studio-live-unreal-engine#28]
I have download the Rokoko Plug in for UE5  and transfer the plug files to my project but the  files are not compiling. And that I need to try rebuilding from source manually. I  have tried opening the project folder that came with , but I have the same problem.

**Comment by GustavBlack** [comment]
Yeah I'm having the same issue, is that ok if I change the version in the source to UE5.0.0EA2 ? It's getting caught on the version name...

**Comment by lancelotcq2** [comment]
There are comments on the youtube page as well saying the plug in doesn't work in 5 and I am having the same issue.  I can't seem to resolve it.  I wonder if anyone from Rokoko will address this?

**Comment by SpirosK-RKK** [comment]
Hi all, please use our new specific-for-UE5EA plugin, released 8 days ago.
You can find it at the Releases page of this project.

**Comment by SpirosK-RKK** [comment]
If you will compile from code, please use the "5.0EA" branch.

**Comment by holymoses0v0** [comment]
For anyone having trouble importing the UE5 plugin from this github repo, here is what I did to get it to work:

- Download source from Github (if you are on the main repo page, click Tags and select the one tagged with UE5.0
- With the source code on your computer, you should have a folder called SmartSuit. I recommend saving this folder to a spot on your computer such as "UE5-pluigins" or someplace, so that if you have multiple projects that you want to use the plugin with, instead of re-downloading this plugin and doing these steps again, you can just copy-paste from the compiled version which we will create now.

- Now that you have a the source code downloaded, you need to locate your UE5 Batch Files. I found this by going C -> Program Files -> Epic Games -> UE_5.0EA -> Engine -> Build -> BatchFiles . If you have trouble locating it, right click on the UE5 launcher and click properties which should help you locate the folder and then just click back to the Engine Folder and then click into BatchFiles.


- After you have located the BatchFiles, follow this video for recompiling the source code

https://www.youtube.com/watch?v=WtfLfYY_k2Y


(If video is deleted, you essentially need to open a Command window under the BatchFIles folder and run the BuildVAT plugin command and pass in the Smartsuit.uplugin file as the command line argument)


After running the BuildVat command, you should now have a new folder with the re-compiled plugin. Now you can just copy-paste this folder into your projects Plugins folder and you should now have the UE5 Smartsuit plugin in your UE5 project.


I hope that helps. It took me hours to figure this out and get it working so just wanted to share how I got it resolved.

**Comment by SpirosK-RKK** [comment]
Thank you for contributing to the community @holymoses0v0 .
