### ISSUE TITLE
Unreal Engine 5.2 Support

### ISSUE THREAD

**Issue by DaveWillie** [Rokoko/rokoko-studio-live-unreal-engine#45]
Currently not supported for Unreal Engine 5.2, how soon will it be updated please?

**Comment by baronlanteigne** [comment]
Yeah. I would appreciate too.

Someone on discord mentioned that it's possible to build the 5.1 plugin with 5.2 but I did not succeed.

I tried the Automation method found here: https://dev.epicgames.com/community/learning/tutorials/qz93/unreal-engine-building-plugins

I used the plugin for 5.1 found here and I got the following errors:

`[2/3] Compile [x64] Module.Smartsuit.2_of_3.cpp
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\RokokoStudioCommandAPI.cpp(116): warning C4996: PRAGMA_DISABLE_OPTIMIZATION has been deprecated. Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\RokokoStudioCommandAPI.cpp(123): warning C4996: PRAGMA_ENABLE_OPTIMIZATION has been deprecated. Use UE_ENABLE_OPTIMIZATION for temporary development or UE_ENABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitBlueprintLibrary.cpp(140): error C2027: use of undefined type 'USkeletalMesh'
C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Engine\Public\Animation\AnimTrace.h(23): note: see declaration of 'USkeletalMesh'
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitBlueprintLibrary.cpp(159): error C2027: use of undefined type 'USkeletalMesh'
C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Engine\Public\Animation\AnimTrace.h(23): note: see declaration of 'USkeletalMesh'
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitPoseNode.cpp(362): warning C4996: PRAGMA_DISABLE_OPTIMIZATION has been deprecated. Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitPoseNode.cpp(835): warning C4996: PRAGMA_ENABLE_OPTIMIZATION has been deprecated. Use UE_ENABLE_OPTIMIZATION for temporary development or UE_ENABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitPoseNode.cpp(1213): warning C4996: PRAGMA_DISABLE_OPTIMIZATION has been deprecated. Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitPoseNode.cpp(1223): warning C4996: PRAGMA_ENABLE_OPTIMIZATION has been deprecated. Use UE_ENABLE_OPTIMIZATION for temporary development or UE_ENABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitReceiver.cpp(191): warning C4996: PRAGMA_DISABLE_OPTIMIZATION has been deprecated. Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\SmartsuitReceiver.cpp(226): warning C4996: PRAGMA_ENABLE_OPTIMIZATION has been deprecated. Use UE_ENABLE_OPTIMIZATION for temporary development or UE_ENABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\VirtualProductionSource.cpp(1176): warning C4996: PRAGMA_DISABLE_OPTIMIZATION has been deprecated. Use UE_DISABLE_OPTIMIZATION for temporary development or UE_DISABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
C:\Work\Unreal\temp\Smartsuit\HostProject\Plugins\Smartsuit\Source\Smartsuit\Private\VirtualProductionSource.cpp(1434): warning C4996: PRAGMA_ENABLE_OPTIMIZATION has been deprecated. Use UE_ENABLE_OPTIMIZATION for temporary development or UE_ENABLE_OPTIMIZATION_SHIP to submit Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.`

**Comment by Chris528** [comment]
try downloading the 5.2 experimental branch and build using build_plugin.bat

**Comment by baronlanteigne** [comment]
Oh I'm down.. but where do I find the experimental branch?

Is it the 5.2_preview-1 branch on epic's github?

**Comment by baronlanteigne** [comment]
@DaveWillie so I was able to rebuild the UE 5.1 plugin with 5.2. I had to use a C++ 5.2.1 project and simply opening the project with the plugin in its directory worked. I haven't used the plugin just yet but it seems good to go.

Ideally someone from the Rokoko team can just rebuild and post here and publish on the marketplace? It's not much work and it would save everyone time.

**Comment by ChromeAndroid** [comment]
> @DaveWillie so I was able to rebuild the UE 5.1 plugin with 5.2. I had to use a C++ 5.2.1 project and simply opening the project with the plugin in its directory worked. I haven't used the plugin just yet but it seems good to go.
> 
> Ideally someone from the Rokoko team can just rebuild and post here and publish on the marketplace? It's not much work and it would save everyone time.

Have you had time to try it out? Was just curious if you could confirm that it is fully functional.

**Comment by baronlanteigne** [comment]
Yes. No Plugin related issues so far. I haven't bothered rebuilding for 5.2 either, I just click ok when prompted about the plugin being made for 5.1.

It's unfortunate the Rokoko team can't be bothered to update the plugin here and on the marketplace.

**Comment by SergeiSolokhin** [comment]
the plugin has been updated on github and official marketplace
